In [28]:
import pandas as pd

In [29]:
import plotly.express as px

In [53]:
import altair as alt

In [30]:
df = pd.read_csv('data/read_book.csv')

In [31]:
df

,FLAG_NM,FLAG_VALUE,HLDY_AT,BOOK_TY_NM,EXAMIN_CO,NON_READ_RT,THIRTY_MNT_BELO_READ_RT,ONE_TIME_BELO_READ_RT,TWO_TIME_BELO_READ_RT,THREE_TIME_BELO_READ_RT,FOUR_TIME_BELO_READ_RT,FIVE_TIME_BELO_READ_RT,FIVE_TIME_ABOVE_READ_RT,AVRG_READ_MNT_VALUE
0,지역,서울,N,종이책,1137,61.6,13.3,12.9,9.8,2.1,0.2,0.0,0.0,15.2
1,지역,부산,N,종이책,392,81.1,5.9,9.0,3.7,0.2,0.0,0.0,0.0,6.3
2,지역,대구,N,종이책,279,45.8,15.6,26.6,12.0,0.0,0.0,0.0,0.0,17.8
3,지역,인천,N,종이책,341,75.0,7.6,8.2,8.9,0.3,0.0,0.0,0.0,10.3
4,지역,광주,N,종이책,168,68.3,8.1,14.7,8.2,0.7,0.0,0.0,0.0,11.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,연령,중등2학년,Y,오디오북,357,93.6,0.9,1.9,3.1,0.2,0.0,0.2,0.0,3.7
182,연령,중등3학년,Y,오디오북,344,88.7,1.4,2.5,3.9,2.4,0.9,0.2,0.0,8.6
183,연령,고등1학년,Y,오디오북,392,94.5,0.7,2.1,1.8,0.2,0.2,0.2,0.3,4.2
184,연령,고등2학년,Y,오디오북,364,91.6,2.0,0.9,3.5,1.5,0.2,0.2,0.1,6.0
185,연령,고등3학년,Y,오디오북,352,90.1,0.7,2.3,4.4,1.8,0.2,0.2,0.3,7.6

In [32]:
df.columns

Index(['FLAG_NM', 'FLAG_VALUE', 'HLDY_AT', 'BOOK_TY_NM', 'EXAMIN_CO',
       'NON_READ_RT', 'THIRTY_MNT_BELO_READ_RT', 'ONE_TIME_BELO_READ_RT',
       'TWO_TIME_BELO_READ_RT', 'THREE_TIME_BELO_READ_RT',
       'FOUR_TIME_BELO_READ_RT', 'FIVE_TIME_BELO_READ_RT',
       'FIVE_TIME_ABOVE_READ_RT', 'AVRG_READ_MNT_VALUE'],
      dtype='object')

In [33]:
df.loc

In [34]:
df.BOOK_TY_NM.unique()

array(['종이책', '전자책', '오디오북'], dtype=object)

In [35]:
df.BOOK_TY_NM.nunique()

3

In [36]:
df

,FLAG_NM,FLAG_VALUE,HLDY_AT,BOOK_TY_NM,EXAMIN_CO,NON_READ_RT,THIRTY_MNT_BELO_READ_RT,ONE_TIME_BELO_READ_RT,TWO_TIME_BELO_READ_RT,THREE_TIME_BELO_READ_RT,FOUR_TIME_BELO_READ_RT,FIVE_TIME_BELO_READ_RT,FIVE_TIME_ABOVE_READ_RT,AVRG_READ_MNT_VALUE
0,지역,서울,N,종이책,1137,61.6,13.3,12.9,9.8,2.1,0.2,0.0,0.0,15.2
1,지역,부산,N,종이책,392,81.1,5.9,9.0,3.7,0.2,0.0,0.0,0.0,6.3
2,지역,대구,N,종이책,279,45.8,15.6,26.6,12.0,0.0,0.0,0.0,0.0,17.8
3,지역,인천,N,종이책,341,75.0,7.6,8.2,8.9,0.3,0.0,0.0,0.0,10.3
4,지역,광주,N,종이책,168,68.3,8.1,14.7,8.2,0.7,0.0,0.0,0.0,11.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,연령,중등2학년,Y,오디오북,357,93.6,0.9,1.9,3.1,0.2,0.0,0.2,0.0,3.7
182,연령,중등3학년,Y,오디오북,344,88.7,1.4,2.5,3.9,2.4,0.9,0.2,0.0,8.6
183,연령,고등1학년,Y,오디오북,392,94.5,0.7,2.1,1.8,0.2,0.2,0.2,0.3,4.2
184,연령,고등2학년,Y,오디오북,364,91.6,2.0,0.9,3.5,1.5,0.2,0.2,0.1,6.0
185,연령,고등3학년,Y,오디오북,352,90.1,0.7,2.3,4.4,1.8,0.2,0.2,0.3,7.6

In [37]:
df.columns[1]

'FLAG_VALUE'

In [38]:
df

,FLAG_NM,FLAG_VALUE,HLDY_AT,BOOK_TY_NM,EXAMIN_CO,NON_READ_RT,THIRTY_MNT_BELO_READ_RT,ONE_TIME_BELO_READ_RT,TWO_TIME_BELO_READ_RT,THREE_TIME_BELO_READ_RT,FOUR_TIME_BELO_READ_RT,FIVE_TIME_BELO_READ_RT,FIVE_TIME_ABOVE_READ_RT,AVRG_READ_MNT_VALUE
0,지역,서울,N,종이책,1137,61.6,13.3,12.9,9.8,2.1,0.2,0.0,0.0,15.2
1,지역,부산,N,종이책,392,81.1,5.9,9.0,3.7,0.2,0.0,0.0,0.0,6.3
2,지역,대구,N,종이책,279,45.8,15.6,26.6,12.0,0.0,0.0,0.0,0.0,17.8
3,지역,인천,N,종이책,341,75.0,7.6,8.2,8.9,0.3,0.0,0.0,0.0,10.3
4,지역,광주,N,종이책,168,68.3,8.1,14.7,8.2,0.7,0.0,0.0,0.0,11.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,연령,중등2학년,Y,오디오북,357,93.6,0.9,1.9,3.1,0.2,0.0,0.2,0.0,3.7
182,연령,중등3학년,Y,오디오북,344,88.7,1.4,2.5,3.9,2.4,0.9,0.2,0.0,8.6
183,연령,고등1학년,Y,오디오북,392,94.5,0.7,2.1,1.8,0.2,0.2,0.2,0.3,4.2
184,연령,고등2학년,Y,오디오북,364,91.6,2.0,0.9,3.5,1.5,0.2,0.2,0.1,6.0
185,연령,고등3학년,Y,오디오북,352,90.1,0.7,2.3,4.4,1.8,0.2,0.2,0.3,7.6

In [39]:
df = df.drop(labels = 'HLDY_AT', axis = 1  )

In [40]:
df

,FLAG_NM,FLAG_VALUE,BOOK_TY_NM,EXAMIN_CO,NON_READ_RT,THIRTY_MNT_BELO_READ_RT,ONE_TIME_BELO_READ_RT,TWO_TIME_BELO_READ_RT,THREE_TIME_BELO_READ_RT,FOUR_TIME_BELO_READ_RT,FIVE_TIME_BELO_READ_RT,FIVE_TIME_ABOVE_READ_RT,AVRG_READ_MNT_VALUE
0,지역,서울,종이책,1137,61.6,13.3,12.9,9.8,2.1,0.2,0.0,0.0,15.2
1,지역,부산,종이책,392,81.1,5.9,9.0,3.7,0.2,0.0,0.0,0.0,6.3
2,지역,대구,종이책,279,45.8,15.6,26.6,12.0,0.0,0.0,0.0,0.0,17.8
3,지역,인천,종이책,341,75.0,7.6,8.2,8.9,0.3,0.0,0.0,0.0,10.3
4,지역,광주,종이책,168,68.3,8.1,14.7,8.2,0.7,0.0,0.0,0.0,11.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,연령,중등2학년,오디오북,357,93.6,0.9,1.9,3.1,0.2,0.0,0.2,0.0,3.7
182,연령,중등3학년,오디오북,344,88.7,1.4,2.5,3.9,2.4,0.9,0.2,0.0,8.6
183,연령,고등1학년,오디오북,392,94.5,0.7,2.1,1.8,0.2,0.2,0.2,0.3,4.2
184,연령,고등2학년,오디오북,364,91.6,2.0,0.9,3.5,1.5,0.2,0.2,0.1,6.0
185,연령,고등3학년,오디오북,352,90.1,0.7,2.3,4.4,1.8,0.2,0.2,0.3,7.6

In [41]:
df = df.rename(columns={'BOOK_TY_NM':'책 형태'})

In [42]:
df

,FLAG_NM,FLAG_VALUE,책 형태,EXAMIN_CO,NON_READ_RT,THIRTY_MNT_BELO_READ_RT,ONE_TIME_BELO_READ_RT,TWO_TIME_BELO_READ_RT,THREE_TIME_BELO_READ_RT,FOUR_TIME_BELO_READ_RT,FIVE_TIME_BELO_READ_RT,FIVE_TIME_ABOVE_READ_RT,AVRG_READ_MNT_VALUE
0,지역,서울,종이책,1137,61.6,13.3,12.9,9.8,2.1,0.2,0.0,0.0,15.2
1,지역,부산,종이책,392,81.1,5.9,9.0,3.7,0.2,0.0,0.0,0.0,6.3
2,지역,대구,종이책,279,45.8,15.6,26.6,12.0,0.0,0.0,0.0,0.0,17.8
3,지역,인천,종이책,341,75.0,7.6,8.2,8.9,0.3,0.0,0.0,0.0,10.3
4,지역,광주,종이책,168,68.3,8.1,14.7,8.2,0.7,0.0,0.0,0.0,11.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,연령,중등2학년,오디오북,357,93.6,0.9,1.9,3.1,0.2,0.0,0.2,0.0,3.7
182,연령,중등3학년,오디오북,344,88.7,1.4,2.5,3.9,2.4,0.9,0.2,0.0,8.6
183,연령,고등1학년,오디오북,392,94.5,0.7,2.1,1.8,0.2,0.2,0.2,0.3,4.2
184,연령,고등2학년,오디오북,364,91.6,2.0,0.9,3.5,1.5,0.2,0.2,0.1,6.0
185,연령,고등3학년,오디오북,352,90.1,0.7,2.3,4.4,1.8,0.2,0.2,0.3,7.6

In [43]:
df = df.tail(83)

In [44]:
df

,FLAG_NM,FLAG_VALUE,책 형태,EXAMIN_CO,NON_READ_RT,THIRTY_MNT_BELO_READ_RT,ONE_TIME_BELO_READ_RT,TWO_TIME_BELO_READ_RT,THREE_TIME_BELO_READ_RT,FOUR_TIME_BELO_READ_RT,FIVE_TIME_BELO_READ_RT,FIVE_TIME_ABOVE_READ_RT,AVRG_READ_MNT_VALUE
103,연령,30-39세,종이책,964,59.2,11.1,17.9,10.6,1.2,0.0,0.0,0.0,15.2
104,연령,40-49세,종이책,1123,68.5,9.5,11.8,9.2,0.9,0.0,0.0,0.0,12.1
105,연령,50-59세,종이책,1173,76.0,6.3,8.7,7.9,1.0,0.0,0.0,0.0,10.3
106,연령,60세이상,종이책,1724,80.3,4.2,7.4,6.5,1.1,0.5,0.0,0.0,9.5
107,연령,19-29세,전자책,1016,59.9,6.9,13.5,18.2,1.3,0.1,0.0,0.0,18.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,연령,중등2학년,오디오북,357,93.6,0.9,1.9,3.1,0.2,0.0,0.2,0.0,3.7
182,연령,중등3학년,오디오북,344,88.7,1.4,2.5,3.9,2.4,0.9,0.2,0.0,8.6
183,연령,고등1학년,오디오북,392,94.5,0.7,2.1,1.8,0.2,0.2,0.2,0.3,4.2
184,연령,고등2학년,오디오북,364,91.6,2.0,0.9,3.5,1.5,0.2,0.2,0.1,6.0
185,연령,고등3학년,오디오북,352,90.1,0.7,2.3,4.4,1.8,0.2,0.2,0.3,7.6

In [45]:
df

,FLAG_NM,FLAG_VALUE,책 형태,EXAMIN_CO,NON_READ_RT,THIRTY_MNT_BELO_READ_RT,ONE_TIME_BELO_READ_RT,TWO_TIME_BELO_READ_RT,THREE_TIME_BELO_READ_RT,FOUR_TIME_BELO_READ_RT,FIVE_TIME_BELO_READ_RT,FIVE_TIME_ABOVE_READ_RT,AVRG_READ_MNT_VALUE
103,연령,30-39세,종이책,964,59.2,11.1,17.9,10.6,1.2,0.0,0.0,0.0,15.2
104,연령,40-49세,종이책,1123,68.5,9.5,11.8,9.2,0.9,0.0,0.0,0.0,12.1
105,연령,50-59세,종이책,1173,76.0,6.3,8.7,7.9,1.0,0.0,0.0,0.0,10.3
106,연령,60세이상,종이책,1724,80.3,4.2,7.4,6.5,1.1,0.5,0.0,0.0,9.5
107,연령,19-29세,전자책,1016,59.9,6.9,13.5,18.2,1.3,0.1,0.0,0.0,18.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,연령,중등2학년,오디오북,357,93.6,0.9,1.9,3.1,0.2,0.0,0.2,0.0,3.7
182,연령,중등3학년,오디오북,344,88.7,1.4,2.5,3.9,2.4,0.9,0.2,0.0,8.6
183,연령,고등1학년,오디오북,392,94.5,0.7,2.1,1.8,0.2,0.2,0.2,0.3,4.2
184,연령,고등2학년,오디오북,364,91.6,2.0,0.9,3.5,1.5,0.2,0.2,0.1,6.0
185,연령,고등3학년,오디오북,352,90.1,0.7,2.3,4.4,1.8,0.2,0.2,0.3,7.6

In [46]:
df = df.drop(labels = 'FLAG_NM', axis = 1  )

In [47]:
df

,FLAG_VALUE,책 형태,EXAMIN_CO,NON_READ_RT,THIRTY_MNT_BELO_READ_RT,ONE_TIME_BELO_READ_RT,TWO_TIME_BELO_READ_RT,THREE_TIME_BELO_READ_RT,FOUR_TIME_BELO_READ_RT,FIVE_TIME_BELO_READ_RT,FIVE_TIME_ABOVE_READ_RT,AVRG_READ_MNT_VALUE
103,30-39세,종이책,964,59.2,11.1,17.9,10.6,1.2,0.0,0.0,0.0,15.2
104,40-49세,종이책,1123,68.5,9.5,11.8,9.2,0.9,0.0,0.0,0.0,12.1
105,50-59세,종이책,1173,76.0,6.3,8.7,7.9,1.0,0.0,0.0,0.0,10.3
106,60세이상,종이책,1724,80.3,4.2,7.4,6.5,1.1,0.5,0.0,0.0,9.5
107,19-29세,전자책,1016,59.9,6.9,13.5,18.2,1.3,0.1,0.0,0.0,18.6
...,...,...,...,...,...,...,...,...,...,...,...,...
181,중등2학년,오디오북,357,93.6,0.9,1.9,3.1,0.2,0.0,0.2,0.0,3.7
182,중등3학년,오디오북,344,88.7,1.4,2.5,3.9,2.4,0.9,0.2,0.0,8.6
183,고등1학년,오디오북,392,94.5,0.7,2.1,1.8,0.2,0.2,0.2,0.3,4.2
184,고등2학년,오디오북,364,91.6,2.0,0.9,3.5,1.5,0.2,0.2,0.1,6.0
185,고등3학년,오디오북,352,90.1,0.7,2.3,4.4,1.8,0.2,0.2,0.3,7.6

In [48]:
df = df.rename(columns={'FLAG_VALUE':'연령'})

In [49]:
df

,연령,책 형태,EXAMIN_CO,NON_READ_RT,THIRTY_MNT_BELO_READ_RT,ONE_TIME_BELO_READ_RT,TWO_TIME_BELO_READ_RT,THREE_TIME_BELO_READ_RT,FOUR_TIME_BELO_READ_RT,FIVE_TIME_BELO_READ_RT,FIVE_TIME_ABOVE_READ_RT,AVRG_READ_MNT_VALUE
103,30-39세,종이책,964,59.2,11.1,17.9,10.6,1.2,0.0,0.0,0.0,15.2
104,40-49세,종이책,1123,68.5,9.5,11.8,9.2,0.9,0.0,0.0,0.0,12.1
105,50-59세,종이책,1173,76.0,6.3,8.7,7.9,1.0,0.0,0.0,0.0,10.3
106,60세이상,종이책,1724,80.3,4.2,7.4,6.5,1.1,0.5,0.0,0.0,9.5
107,19-29세,전자책,1016,59.9,6.9,13.5,18.2,1.3,0.1,0.0,0.0,18.6
...,...,...,...,...,...,...,...,...,...,...,...,...
181,중등2학년,오디오북,357,93.6,0.9,1.9,3.1,0.2,0.0,0.2,0.0,3.7
182,중등3학년,오디오북,344,88.7,1.4,2.5,3.9,2.4,0.9,0.2,0.0,8.6
183,고등1학년,오디오북,392,94.5,0.7,2.1,1.8,0.2,0.2,0.2,0.3,4.2
184,고등2학년,오디오북,364,91.6,2.0,0.9,3.5,1.5,0.2,0.2,0.1,6.0
185,고등3학년,오디오북,352,90.1,0.7,2.3,4.4,1.8,0.2,0.2,0.3,7.6